### ISSUE TITLE
Device does not open the site

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#140]
Steps:
1. Open http://stf-stage.solvd.com
2. Enter your login and password
3. Open any  ios device e.g iPhone 8
4.Tap on a link in the navigation bar and enter any site e.g.  google.com
Actual result: Device does not open the site
<img width="939" alt="Screen Shot 2020-03-24 at 17 44 08" src="https://user-images.githubusercontent.com/50950954/77438782-4dedc800-6df7-11ea-8116-584de3932566.png">

**Comment by vdelendik** [comment]
configuration issues fixed: http://stage.solvd.com/stf

**Comment by dhreben** [comment]
Please double-check ios node

**Comment by vdelendik** [comment]
fixed in scope of global refactoring for 2.0

**Comment by dhreben** [comment]
The issue was resolved with the assistance of the Siri function

**Comment by dhreben** [comment]
Reopened after trying to open any site via navigation

```
2023-04-18T11:44:37.575Z INF/util:lifecycle 28 [d6afc.......b9b6ebb11] Winding down for graceful exit, with optional error :  StatusCodeError: 500 - {"value":{"error":"unknown error","message":"Error Domain=com.apple.dt.xctest.ui-testing.error Code=10401 \"Device does not have the capability to open the default app from a url\" UserInfo={NSLocalizedDescription=Device does not have the capability to open the default app from a url}","traceback":""},"sessionId":"E2446067-CA83-4394-BD00-82583B9CFEF1"}
    at new StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 500,
  error: {
    value: {
      error: 'unknown error',
      message: 'Error Domain=com.apple.dt.xctest.ui-testing.error Code=10401 "Device does not have the capability to open the default app from a url" UserInfo={NSLocalizedDescription=Device does not have the capability to open the default app from a url}',
      traceback: ''
    },
    sessionId: 'E2446067-CA83-4394-BD00-82583B9CFEF1'
  },
  options: {
    method: 'POST',
    uri: 'http://appium:8100/session/E2446067-CA83-4394-BD00-82583B9CFEF1/url',
    body: { url: 'http://google.com' },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 15633,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Server',
      'WebDriverAgent/1.0',
      'Content-Type',
      'application/json;charset=UTF-8',
      'Access-Control-Allow-Origin',
      '*',
      'Date',
      'Tue, 18 Apr 2023 11:44:37 GMT',
      'Access-Control-Allow-Headers',
      'Content-Type, X-Requested-With',
      'Accept-Ranges',
      'bytes',
      'Content-Length',
      '389',
      'Connection',
      'close'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'appium',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 15633,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /session/E2446067-CA83-4394-BD00-82583B9CFEF1/url HTTP/1.1\r\n' +
        'host: appium:8100\r\n' +
        'accept: application/json\r\n' +
        'content-type: application/json\r\n' +
        'content-length: 27\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/session/E2446067-CA83-4394-BD00-82583B9CFEF1/url',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'appium',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      uri: [Url],
      body: '{"url":"http://google.com"}',
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: '8100',
      host: 'appium',
      path: '/session/E2446067-CA83-4394-BD00-82583B9CFEF1/url',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://appium:8100/session/E2446067-CA83-4394-BD00-82583B9CFEF1/url',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: 'appium:8100',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      value: [Object],
      sessionId: 'E2446067-CA83-4394-BD00-82583B9CFEF1'
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      server: 'WebDriverAgent/1.0',
      'content-type': 'application/json;charset=UTF-8',
      'access-control-allow-origin': '*',
      date: 'Tue, 18 Apr 2023 11:44:37 GMT',
      'access-control-allow-headers': 'Content-Type, X-Requested-With',
      'accept-ranges': 'bytes',
      'content-length': '389',
      connection: 'close'
    },
    [Symbol(kHeadersCount)]: 16,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}

```

**Comment by vdelendik** [comment]
@dhreben - please retest again. this button should be disabled in iOS. Make sure to clear cache and cookies in advance

**Comment by ignacionar** [comment]
The `/url` endpoint works incorrectly. Siri isn't an efficient approach to handle it: https://github.com/zebrunner/stf/pull/733

**Comment by dhreben** [comment]
Still repro.According new approach open button still available.

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/736

**Comment by dhreben** [comment]
Verified. Open site button on navigation is disabled

**Comment by ignacionar** [comment]
The `/url` endpoint has been fixed for iOS 17 devices ([related discussion](https://developer.apple.com/forums/thread/25355#:~:text=Hello!%20As%20of%20the%20release%20of%20Xcode%2015%20and%20iOS%2017%2C%20many%20of%20the%20issues%20with%20these%20APIs%20should%20be%20resolved.))

This PR enables the navigation input only for iOS 17: https://github.com/zebrunner/stf/pull/820

**Comment by dhreben** [comment]
Reopened
According the last changed https://github.com/zebrunner/stf/pull/820 navigation tab is  still enabled for iphone up to 17 version
