### ISSUE TITLE
iOS: 1st session open can't determine window size as session still null

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#174]
```
2020-12-18T10:37:05.867Z INF/wdaClient 9996 [b09fa26acc4c3f777e9b8b49e3348b7243f862b5] window size: http://192.168.89.19:20001/session/null/window/size
Unhandled rejection TypeError: Cannot read property 'then' of undefined
    at chain.then.catch.result (/Users/idmcloud/tools/stf/lib/units/ios-device/plugins/screen/stream.js:70:19)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at getRequestStream (/Users/idmcloud/tools/stf/lib/units/ios-device/plugins/screen/stream.js:65:19)
    at WebSocketServer.wss.on (/Users/idmcloud/tools/stf/lib/units/ios-device/plugins/screen/stream.js:116:9)
    at emitTwo (events.js:126:13)
    at WebSocketServer.emit (events.js:214:7)
    at handleUpgrade (/Users/idmcloud/tools/stf/node_modules/ws/lib/WebSocketServer.js:87:16)
    at WebSocketServer.completeUpgrade (/Users/idmcloud/tools/stf/node_modules/ws/lib/WebSocketServer.js:288:5)
    at WebSocketServer.handleUpgrade (/Users/idmcloud/tools/stf/node_modules/ws/lib/WebSocketServer.js:227:10)
    at Server.WebSocketServer._ultron.on (/Users/idmcloud/tools/stf/node_modules/ws/lib/WebSocketServer.js:86:14)
    at emitThree (events.js:136:13)
    at Server.emit (events.js:217:7)
    at onParserExecuteCommon (_http_server.js:542:14)
    at onParserExecute (_http_server.js:496:3)
2020-12-18T10:37:05.917Z INF/wdaClient 9996 [b09fa26acc4c3f777e9b8b49e3348b7243f862b5] baseUrl : http://192.168.89.19:20001

```

**Comment by vdelendik** [comment]
fixed. we don't do `size` call during device occupation at all.
during the testing inspect stf logs on first device occupation. No exception should appear and session should be generated in 1-2 seconds with valid id

**Comment by dhreben** [comment]
Fixed:

**Test scenario:**

1.cd ../stf/
2.npm install
3.cd ../mcloud-ios/
4.rm ./logs/*stf*
5../killAllSTF.sh 
6.tail -n 100 -f ./logs/iPhone_8_stf.log
7.open Iphone 8 on  [stage.solvd.com/stf](url)
8.Tap to any  icon.

**Expected result:** Session generated in 1-2 seconds with valid id.

<img width="1100" alt="Screenshot 2020-12-21 at 19 20 37" src="https://user-images.githubusercontent.com/50950954/102798053-9e637780-43c1-11eb-9605-82de27a707ad.png">
