### ISSUE TITLE
Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#241]
stf started for iOS device inside Linux container shows:
```
module.js:550
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/stf/lib/cli/index.js:5:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by vdelendik** [comment]
fixed. it might be tested when consolidated `zebrunner/device` image is ready

**Comment by vdelendik** [comment]
still present in spite of the update package.json, reopening...
