### ISSUE TITLE
upgrade outdated dependencies

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#251]
let's start global movement to new versions based on bot suggestions.
let's start from:
protobuf - https://github.com/zebrunner/stf/pull/91/files;
...

**Comment by vdelendik** [comment]
make all changes carefully with testing using 3rd branches, for example new protobufjs fail for android devices asap:
```
2021-12-03T17:41:51.904Z INF/device 87 [R28M1384YQY] Fully operational
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: keyOrObj.hasOwnProperty is not a function
    at MessagePrototype.set (/app/node_modules/protobufjs/dist/protobuf.js:2482:42)
    at new Message (/app/node_modules/protobufjs/dist/protobuf.js:2411:34)
    at Router.<anonymous> (/app/lib/units/device/plugins/solo.js:43:11)
    at Router.emit (/app/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/app/lib/wire/router.js:35:12)
    at emitTwo (events.js:126:13)
    at exports.Socket.emit (events.js:214:7)
    at exports.Socket.Socket._flushRead (/app/node_modules/zmq/lib/index.js:638:15)
    at exports.Socket.Socket._flushReads (/app/node_modules/zmq/lib/index.js:676:23)
    at Object._zmq.onReadReady (/app/node_modules/zmq/lib/index.js:297:10)
```

so migration path should be:
1. sync bot and develop sources in 3rd branch
2. deploy new device container
3. restart android/ios devices
4. use device manually in stf (basic acceptance)
4. run automation acceptance on both platforms

**Comment by vdelendik** [comment]
pull latest changes from https://github.com/DeviceFarmer/stf/releases/tag/v3.6.4

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/450
the most critical change is moving from node8 to node17

**Comment by dhreben** [comment]
Verified.
```
root@e45.....a:/opt# node --version 
v17.9.0
```
