### ISSUE TITLE
ios: typeKeys is too slow

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#253]
using wda we send keys one by one with default speed (frequency).
let's investigate what might be done to make typing as close as possible to real time

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/pull/265
I reused 2 consequent calls where 1st one detect active element/field and 2nd send new value to the filed.

During the testing:
1. activate text field in any application or browser. Type one by one 
-> using adequate speed and quality keys are delivered to the element
2. click home button to have nothing selected for the typing and type something
-> no errors etc, type operations ignored, appropriate line should be displayed in the logs: `no active element discovered - ignoring type keys: ...`

**Comment by okamara** [comment]
Verified, typing is slow and created a separate ticket https://github.com/zebrunner/stf/issues/268

**Comment by vdelendik** [comment]
moved to 2.1 as the most important typing inside iOS native applications are pretty fast and stable. in scope of this ticket let's investigate possibility to send words instead of each char for both fast and slow wda type keys methods

**Comment by vdelendik** [comment]
@okamara, more mature fix delivered: https://github.com/zebrunner/stf/pull/282/files

Based on by investigation I've found that typeing on default springboard screen is too slow (5-6s per each key). I.e. again 10 keys leads to 50-60s sleep.
So reorganized approach a little bit adding active app verification and ignoring typeKeys requests when default iPhone screen is active... So new testing scenario is:
1. Open any iPhone, tap into the default screen and do type 5-10 times
-> nothing is crashed, no sleep/delay and you can proceed with the next operations aka swipe, open app etc
2. During typing inside default screen please also inspect device container logs
-> every key type should produce exception like below:
```
2021-12-22T23:10:54.480Z ERR/wdaClient 114 [d6afc6b3a65584ca0813eb8957c6479b9b6ebb11] Error: ignoring typeKey as springboard is active!
    at handleRequest.then.response (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:83:21)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Promise (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:78:12)
From previous event:
    at Object.typeKey (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:71:16)
    at Router.sub.on.wirerouter.on.on.on.on.on.on.on.on (/opt/lib/units/ios-device/plugins/wda.js:56:19)
    at Router.emit (/opt/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/opt/lib/wire/router.js:35:12)
    at emitTwo (events.js:131:20)
    at exports.Socket.emit (events.js:214:7)
    at exports.Socket.Socket._flushRead (/opt/node_modules/zmq/lib/index.js:638:15)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zmq/lib/index.js:676:23)
    at Object._zmq.onReadReady (/opt/node_modules/zmq/lib/index.js:297:10)
```
3. Activate `Notes` application and generate new note. 
-> Every type key operation should be in a sec (pretty fast)
4. Open browser and yahoo.com web site and try to type into the search field
-> type is pretty slow (1-2s per each key is expected)

**Comment by dhreben** [comment]
Fixed
