### ISSUE TITLE
ios: Impossible enter password correctly for apple ID

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#269]
Steps:
1. Open iphone device via stf
2. Open Playmarket app
3. Tap an application to get the app
4. Start enter the password
Actual result: user enter password but it is not visible
Expected result: user enter password and it is visible

<img width="434" alt="Снимок экрана 2021-12-16 в 14 29 18" src="https://user-images.githubusercontent.com/32964663/146378632-cfcdd359-adda-4a2f-9342-1943ef59fb81.png">

**Comment by vdelendik** [comment]
tested on devices and found that:
1. password is typed so we can enter it correctly
2. keyboard exists on device but also not displayed in STF
so as it is not a blocker ticket moved to 2.1

**Comment by vdelendik** [comment]
we ignore typeKey as springboard is detected when we wanna to install something and see apple store credentials dialog.
also keyboard is displayed on device but not visible in STF somehow...
```
2022-08-01T16:32:41.519Z VRB/wdaClient 25 [b09fa26acc4c3f777e9b8b49e3348b7243f862b5] active app: com.apple.springboard
2022-08-01T16:32:41.522Z ERR/wdaClient 25 [b09fa26acc4c3f777e9b8b49e3348b7243f862b5] Error: ignoring typeKey as springboard is active!
    at /opt/lib/units/ios-device/plugins/wda/WdaClient.js:158:21
From previous event:
    at /opt/lib/units/ios-device/plugins/wda/WdaClient.js:153:12
From previous event:
    at Object.typeKey (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:146:16)
    at Router.<anonymous> (/opt/lib/units/ios-device/plugins/wda.js:56:19)
    at Router.emit (/opt/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/opt/lib/wire/router.js:35:12)
    at exports.Socket.emit (node:events:539:35)
    at exports.Socket.Socket._emitMessage (/opt/node_modules/zeromq/lib/index.js:649:15)
    at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:660:10)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
    at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by vdelendik** [comment]
@dhreben, let's test using latest WDA 4.12.0. Feel free to reopen if still is repro

**Comment by dhreben** [comment]
Still repro
Reopened

**Comment by vaclcer** [comment]
Also cannot enter a wifi password. I believe it is the same issue with the same symptoms - the keyboard pops up on the device, but not in STF.

**Comment by ignacionar** [comment]
In `XCUIElementTypeSecureTextField`, the keyboard is present but the screenshot is hardcoded to **not** include the keyboard or the text inside the element.

However, the keyboard works normally in WDA. The element contains the `hasKeyboardFocus` property, so both the keyboard and the element are working fine:

`t =   268.83s Find: Elements matching predicate 'hasKeyboardFocus == 1'
t =   268.83s Find: Identity Binding
t =   268.84s Checking existence of `"Passcode field" SecureTextField``

**Comment by dhreben** [comment]
Won't fix.Closed
