### ISSUE TITLE
capture wda/appium crash asap and exit with status 1 from stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#409]
let's investigate possibility to capture below exception and exit from stf completely
```
2022-04-21T13:25:17.534Z INF/wdaClient 92 [] stopping wda session...
2022-04-21T13:25:17.537Z IMP/device:plugins:screen:stream 92 [] ws on close event
Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.88.124:8100
    at new RequestError (/opt/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/opt/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
From previous event:
    at Object.handleRequest (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:405:16)
    at Object.stopSession (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:126:21)
    at WebSocket.<anonymous> (/opt/lib/units/ios-device/plugins/screen/stream.js:96:21)
    at emitTwo (events.js:131:20)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/opt/node_modules/ws/lib/WebSocket.js:211:10)
    at _receiver.cleanup (/opt/node_modules/ws/lib/WebSocket.js:199:39)
    at Receiver.cleanup (/opt/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/opt/node_modules/ws/lib/WebSocket.js:199:20)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2022-04-21T13:26:14.968Z INF/util:lifecycle 92 [] Winding down for graceful exit, with optional error :  SIGTERM
2022-04-21T13:26:14.974Z IMP/device:plugins:group 92 [] No longer owned by "admin@zebrunner.com"
2022-04-21T13:26:14.975Z INF/device:plugins:group 92 [] Unsubscribing from group channel "lhUKZxbIQAyCJ3pVA1CBTw=="
2022-04-21T13:26:14.976Z WRN/db 92 [] Connection closed
```

**Comment by vdelendik** [comment]
done for use-case when device is currently used in STF.
in this case killing appium or wda inside `appium` container crash stf with exit code 1.
so to test make sure services started and configured correctly and:
1. open iOS device, do basic actions
2. bash into the iOS device appium container and kill wda
`ios kill $WDA_BUNDLEID --udid=$DEVICE_UDID`
-> in STF error should be displayed asap that "device is temporary unavailable"
-> stf container should eb restarted automatically in 30-90s, occupy iOS device and do basic actions
3. bash again into the iOS device appium container and kill appium process
-> again in STF error should be displayed asap that "device is temporary unavailable"
-> stf container should eb restarted automatically in 30-90s, occupy iOS device and do basic actions

**Comment by vdelendik** [comment]
item #3 fixed. to handle #2 correctly submitted [enhamcement](https://github.com/zebrunner/appium/issues/88) to appium.
so better to retested again after fixing appium ticket
