### ISSUE TITLE
capture wda/appium crash asap even if device is not used

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#411]
in #409 we were able to capture wany wda exception in the sate when device is used in STF. That's allowed to do force `process.exit(1)` from ios-device service and initiate valid containers restart on failure.
At the same time changes for #409 coudn't capture state when nobody use device or when device is under automation usage.

In scope of this ticket we have to implement the same logic as in android where missed connection (killed appium, stopped appium container) is detected asap and stf-provider init new `device` service

**Comment by vdelendik** [comment]
android adb tracker in the same way generate such exception:
```
2022-04-21T15:43:19.707Z FTL/util:lifecycle 7 [*] Tracker had an error Error: Connection closed
    at /opt/node_modules/@devicefarmer/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2022-04-21T15:43:19.707Z FTL/util:lifecycle 7 [*] Shutting down due to fatal error with optional error :  undefined
```

**Comment by vdelendik** [comment]
investigate implementation for android in this file: `stf\lib\units\device\plugins\forward\index.js`

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/421. 
Test Scenarios:
1. start and configure everything using develop branch. tail iPhone device container log on Linux
-> approximately every 30s it should have a message like:
`Connected to wda ${options.wdaHost}:${options.wdaPort}`
2. activate device in stf
-> actions are available, you can tap, type etc
3. stop using device via stf
4. disconnect device and start timer
-> tailed device stf log should have error message that unable to connect to wda
-> approx in 20-30s device should be disconnected in stf

**Comment by vdelendik** [comment]
tested successfully

**Comment by vdelendik** [comment]
reopened to find better way to track wda status

**Comment by vdelendik** [comment]
connecting to wda_host:mjpeg_port (--connect-port) is preferable as this connection is not disconnected by foreign host every 30s

**Comment by vdelendik** [comment]
done using socket connection to wda mjpeg port
