### ISSUE TITLE
Error 500: Service is currently unavailable after click all media buttons on STF at iOS

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#465]
**Steps:**

1. Open iOS device on STF
2. Click Advanced input settings
3.  Check that rewind/previous/play/pause/stop/next/fast forward buttons are work

**Actual result:**  Error 500: Service is currently unavailable after click all media buttons on STF at iOS

**NOTE**: iOS device disconnected from STF , after 30sec it  restart and available.

<img width="898" alt="Screenshot 2022-05-16 at 13 05 39" src="https://user-images.githubusercontent.com/50950954/168583410-f5cd8d17-d280-48a5-a80d-8897f197f72f.png">

**STF logs:**

```
2022-05-16T11:06:49.855Z VRB/wdaClient 16 [b09fa2.....62b5] Request has been sent to WDA with data:  {"method":"GET","uri":"http://192.168.89.19:8100/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/batteryInfo","json":true}
2022-05-16T11:07:30.729Z INF/util:lifecycle 16 [[b09fa2.....62b5] Winding down for graceful exit, with optional error :  StatusCodeError: 500 - {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"The button 'media_previous' is unknown. Only the following button names are supported: (\n    home,\n    volumeUp,\n    volumeDown\n)\" UserInfo={NSLocalizedDescription=The button 'media_previous' is unknown. Only the following button names are supported: (\n    home,\n    volumeUp,\n    volumeDown\n)}","traceback":""},"sessionId":"6196F309-A71E-4308-8285-B6DDB8E475ED"}
    at new StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 500,
  error: {
    value: {
      error: 'unknown error',
      message: `Error Domain=com.facebook.WebDriverAgent Code=1 "The button 'media_previous' is unknown. Only the following button names are supported: (\n` +
        '    home,\n' +
        '    volumeUp,\n' +
        '    volumeDown\n' +
        `)" UserInfo={NSLocalizedDescription=The button 'media_previous' is unknown. Only the following button names are supported: (\n` +
        '    home,\n' +
        '    volumeUp,\n' +
        '    volumeDown\n' +
        ')}',
      traceback: ''
    },
    sessionId: '6196F309-A71E-4308-8285-B6DDB8E475ED'
  },
  options: {
    method: 'POST',
    uri: 'http://192.168.89.19:8100/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
    body: { name: 'media_previous' },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 23674,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Server',
      'WebDriverAgent/1.0',
      'Content-Type',
      'application/json;charset=UTF-8',
      'Access-Control-Allow-Origin',
      '*',
      'Date',
      'Mon, 16 May 2022 11:07:30 GMT',
      'Access-Control-Allow-Headers',
      'Content-Type, X-Requested-With',
      'Accept-Ranges',
      'bytes',
      'Content-Length',
      '502',
      'Connection',
      'close'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 23674,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: true,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton HTTP/1.1\r\n' +
        'host: 192.168.89.19:8100\r\n' +
        'accept: application/json\r\n' +
        'content-type: application/json\r\n' +
        'content-length: 25\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.89.19',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      uri: [Url],
      body: '{"name":"media_previous"}',
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: '8100',
      host: '192.168.89.19',
      path: '/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://192.168.89.19:8100/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: '192.168.89.19:8100',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      value: [Object],
      sessionId: '6196F309-A71E-4308-8285-B6DDB8E475ED'
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      server: 'WebDriverAgent/1.0',
      'content-type': 'application/json;charset=UTF-8',
      'access-control-allow-origin': '*',
      date: 'Mon, 16 May 2022 11:07:30 GMT',
      'access-control-allow-headers': 'Content-Type, X-Requested-With',
      'accept-ranges': 'bytes',
      'content-length': '502',
      connection: 'close'
    },
    [Symbol(kHeadersCount)]: 16,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}
2022-05-16T11:07:30.734Z FTL/util:lifecycle 16 [b09fa2.....62b5] Shutting down due to fatal error with optional error :  StatusCodeError: 500 - {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"The button 'media_previous' is unknown. Only the following button names are supported: (\n    home,\n    volumeUp,\n    volumeDown\n)\" UserInfo={NSLocalizedDescription=The button 'media_previous' is unknown. Only the following button names are supported: (\n    home,\n    volumeUp,\n    volumeDown\n)}","traceback":""},"sessionId":"6196F309-A71E-4308-8285-B6DDB8E475ED"}
    at new StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 500,
  error: {
    value: {
      error: 'unknown error',
      message: `Error Domain=com.facebook.WebDriverAgent Code=1 "The button 'media_previous' is unknown. Only the following button names are supported: (\n` +
        '    home,\n' +
        '    volumeUp,\n' +
        '    volumeDown\n' +
        `)" UserInfo={NSLocalizedDescription=The button 'media_previous' is unknown. Only the following button names are supported: (\n` +
        '    home,\n' +
        '    volumeUp,\n' +
        '    volumeDown\n' +
        ')}',
      traceback: ''
    },
    sessionId: '6196F309-A71E-4308-8285-B6DDB8E475ED'
  },
  options: {
    method: 'POST',
    uri: 'http://192.168.89.19:8100/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
    body: { name: 'media_previous' },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 23674,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Server',
      'WebDriverAgent/1.0',
      'Content-Type',
      'application/json;charset=UTF-8',
      'Access-Control-Allow-Origin',
      '*',
      'Date',
      'Mon, 16 May 2022 11:07:30 GMT',
      'Access-Control-Allow-Headers',
      'Content-Type, X-Requested-With',
      'Accept-Ranges',
      'bytes',
      'Content-Length',
      '502',
      'Connection',
      'close'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(async_id_symbol)]: 23674,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: true,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton HTTP/1.1\r\n' +
        'host: 192.168.89.19:8100\r\n' +
        'accept: application/json\r\n' +
        'content-type: application/json\r\n' +
        'content-length: 25\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.89.19',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      uri: [Url],
      body: '{"name":"media_previous"}',
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: '8100',
      host: '192.168.89.19',
      path: '/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://192.168.89.19:8100/session/6196F309-A71E-4308-8285-B6DDB8E475ED/wda/pressButton',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: '192.168.89.19:8100',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      value: [Object],
      sessionId: '6196F309-A71E-4308-8285-B6DDB8E475ED'
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      server: 'WebDriverAgent/1.0',
      'content-type': 'application/json;charset=UTF-8',
      'access-control-allow-origin': '*',
      date: 'Mon, 16 May 2022 11:07:30 GMT',
      'access-control-allow-headers': 'Content-Type, X-Requested-With',
      'accept-ranges': 'bytes',
      'content-length': '502',
      connection: 'close'
    },
    [Symbol(kHeadersCount)]: 16,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}
Exit status: 1

```

**Comment by vdelendik** [comment]
buttons should work only if appropriate video player is active. Otherwise, we have to ignore crashes if possible...

**Comment by dhreben** [comment]
Still repro after use player

<img width="1371" alt="Screenshot 2023-01-16 at 13 18 37" src="https://user-images.githubusercontent.com/50950954/212654854-28305779-0843-4f72-8bd6-c6a1e82e2b5f.png">

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/703

**Issue Research:**

- Volume buttons and mute button didn't work because there were different typos in `pressButton` function (inside `/util/iosutil.js` file) . E.g: `this.pressButton('volumedown')`  =>  `this.pressButton('volumeDown') `

- Simulators and physical devices may have different working endpoints / logs. **According to the docs, in simulators volume buttons can't work while on physical devices they do:** 

https://appium.readthedocs.io/en/stable/en/commands/mobile-command/

<img width="813" alt="volumebuttons" src="https://user-images.githubusercontent.com/85379690/224076935-126c4638-e9d6-4366-a9fd-cd4a2728b115.png">

- As far as I understand, media buttons are not available in WDA. 

QA Recommendations:

- Specify if problems occur on physical devices or simulators.

**Comment by vdelendik** [comment]
changes are merged and `public.ecr.aws/zebrunner/stf:2.4.5-beta4` build. @dhreben, please clone and setup from scratch using CE, branch: develop to test fix.

**Comment by dhreben** [comment]
Closed. 
Volume -+ buttons work well on real iOS devices.
According the media buttons are not available in WDA https://appium.readthedocs.io/en/stable/en/commands/mobile-command/ makes sense to disable its
Opened relevant ticket https://github.com/zebrunner/stf/issues/711
