### ISSUE TITLE
Error: service is currently unavailable! Try your attempt later after install app on iOS via STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#552]
**Steps:**

1. Open STF
2. Open iOS device
3. Click Drop file to upload button

**Actulal result:** Error: service is currently unavailable! Try your attempt later after install app on iOS

![Screenshot 2022-08-05 at 19 25 07](https://user-images.githubusercontent.com/50950954/183120217-b1e1ef0f-98d1-4094-9be6-2d36b4045580.png)

Logs: 

```
2022-08-05T16:26:30.351Z INF/device:plugins:install 19 [000....................02E] Installing application from "/s/apk/d48cf5bc-3f8d-4b09-933b-cbf1daaee27a/9166e7b8d09aa23539410aabc921eaef"
2022-08-05T16:26:30.359Z INF/device:plugins:install 19 [000........................802E] regInfo: {"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"constructed":true,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":0}
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'href')
    at Router.<anonymous> (/opt/lib/units/ios-device/plugins/install.js:107:49)
    at Router.emit (/opt/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/opt/lib/wire/router.js:35:12)
    at exports.Socket.emit (node:events:539:35)
    at exports.Socket.Socket._emitMessage (/opt/node_modules/zeromq/lib/index.js:649:15)
    at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:660:10)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
    at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
    at processImmediate (node:internal/timers:466:21)
Emitted 'error' event on  instance at:
    at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:662:10)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
    at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
    at processImmediate (node:internal/timers:466:21)

Node.js v17.9.0
Exit status: 1
```

**Comment by vdelendik** [comment]
fixed reusing another way to detect protocol and url

**Comment by dhreben** [comment]
Verified. MFP app is installed and launched.

![Screenshot 2022-08-09 at 19 38 37](https://user-images.githubusercontent.com/50950954/183708657-0a2799e5-47bd-47d8-bc66-6fd4c00039b5.png)
