### ISSUE TITLE
Configure auto-healing mechanism for the rethinkdb connection

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/stf#726]
The following feature\functionality could be potentially useful when we have some network issues, for instance when network is down, rethinkdb becomes unavailable and it could be restored back only via manual interactions with required services (e.g. STF).

**Comment by vdelendik** [comment]
@ignacionar, please take a look onto this one as well.
```
2023-04-14T15:58:15.429Z WRN/db 85985 [D77F3CD0-A614-4699-940A-2A7D00AFF164] Connection closed
2023-04-14T15:58:15.433Z INF/db 85985 [D77F3CD0-A614-4699-940A-2A7D00AFF164] Connecting to demo.zebrunner.farm:28015
2023-04-14T15:58:15.440Z INF/db 85985 [D77F3CD0-A614-4699-940A-2A7D00AFF164] Unable to connect to demo.zebrunner.farm:28015
2023-04-14T15:58:15.441Z FTL/db 85985 [D77F3CD0-A614-4699-940A-2A7D00AFF164] No hosts left to try
2023-04-14T15:58:15.442Z FTL/util:lifecycle 85985 [D77F3CD0-A614-4699-940A-2A7D00AFF164] Shutting down due to fatal error with optional error :  undefined
2023-04-14 18:58:15.453 WebDriverAgentRunner-Runner[83623:13538483] Disconnected a client from screenshots broadcast
```

we have to improve stf doing explicit exit on this failure. it should activate recovery as for linux so for mac

**Comment by ignacionar** [comment]
Check this PR: https://github.com/zebrunner/stf/pull/727, when disconnecting from the db it should try to connect every 5 seconds.

**Comment by dhreben** [comment]
Reopened, still repro
Steps:
`docker stop rethinkdb`

 log:
```
023-08-11T12:03:05.016Z INF/db 25 [00008101-000848222187001E] Retrying connection in 5 seconds...
2023-08-11T12:03:10.017Z INF/db 25 [00008101-000848222187001E] Connecting to rethinkdb:28015
2023-08-11T12:03:10.021Z INF/db 25 [00008101-000848222187001E] Unable to connect to rethinkdb:28015
2023-08-11T12:03:10.022Z ERR/db 25 [00008101-000848222187001E] Error: No hosts left to try
    at next (/opt/lib/db/index.js:29:15)
    at /opt/lib/db/index.js:45:18
From previous event:
    at next (/opt/lib/db/index.js:40:15)
    at /opt/lib/db/index.js:50:12
From previous event:
    at connect (/opt/lib/db/index.js:24:4)
    at processImmediate (node:internal/timers:466:21)
2023-08-11T12:03:10.023Z INF/db 25 [00008101-000848222187001E] Retrying connection in 5 seconds...
2023-08-11T12:03:15.029Z INF/db 25 [00008101-000848222187001E] Connecting to rethinkdb:28015
2023-08-11T12:03:15.037Z INF/db 25 [00008101-000848222187001E] Unable to connect to rethinkdb:28015, Exiting...
2023-08-11T12:03:15.039Z FTL/db 25 [00008101-000848222187001E] Cannot read properties of undefined (reading 'on')
2023-08-11T12:03:15.039Z FTL/util:lifecycle 25 [00008101-000848222187001E] Shutting down due to fatal error with optional error :  undefined
Exit status: 1

```

**Comment by vdelendik** [comment]
@dhreben - please tests with rethinkdb restart. there is a limitation in retries so long pause will crash as expected...

**Comment by dhreben** [comment]
Verified.
Steps:
docker restart rethinkdb
rethinkdb restarted and available
