### ISSUE TITLE
AppleTV: connect to wda aborted

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#746]
during opening AppleTV in stf for some devices we can't get response from wda /status end-point.
it seems like we have to increase max allowed time for this operation like we did in appium: https://github.com/zebrunner/appium/issues/171

```
2023-05-15T15:43:20.352Z VRB/wdaClient 59216 [3f...507] Request has been sent to WDA with data:  {"method":"POST","uri":"http://localhost:7441/session","body":{"capabilities":{}},"json":true}
2023-05-15T15:43:20.366Z INF/util:lifecycle 59216 [3f...507] Winding down for graceful exit, with optional error :  RequestError: Error: aborted
    at new RequestError (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/mobile/tools/mcloud-ios/stf/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/mobile/tools/mcloud-ios/stf/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: aborted
      at connResetException (node:internal/errors:691:14)
      at Socket.socketCloseListener (node:_http_client:407:19)
      at Socket.emit (node:events:402:35)
      at TCP.<anonymous> (node:net:687:12) {
    code: 'ECONNRESET'
  },
  error: Error: aborted
      at connResetException (node:internal/errors:691:14)
      at Socket.socketCloseListener (node:_http_client:407:19)
      at Socket.emit (node:events:402:35)
      at TCP.<anonymous> (node:net:687:12) {
    code: 'ECONNRESET'
  },
  options: {
    method: 'GET',
    uri: 'http://localhost:7441/status',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
2023-05-15T15:43:20.370Z FTL/util:lifecycle 59216 [3f507] Shutting down due to fatal error with optional error :  RequestError: Error: aborted
    at new RequestError (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/mobile/tools/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/mobile/tools/mcloud-ios/stf/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/mobile/tools/mcloud-ios/stf/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: aborted
      at connResetException (node:internal/errors:691:14)
      at Socket.socketCloseListener (node:_http_client:407:19)
      at Socket.emit (node:events:402:35)
      at TCP.<anonymous> (node:net:687:12) {
    code: 'ECONNRESET'
  },
  error: Error: aborted
      at connResetException (node:internal/errors:691:14)
      at Socket.socketCloseListener (node:_http_client:407:19)
      at Socket.emit (node:events:402:35)
      at TCP.<anonymous> (node:net:687:12) {
    code: 'ECONNRESET'
  },
  options: {
    method: 'GET',
    uri: 'http://localhost:7441/status',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
```

**Comment by vdelendik** [comment]
just in case issue occurs on the devices which are connected via wi-fi!

**Comment by vdelendik** [comment]
closing as fixed indirectly. we improved a lot size/scale detection

**Comment by dhreben** [comment]
Closed
