### ISSUE TITLE
capture, move to unhelathy state and exit with 0 error code

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#847]
no sense to continue with restarts as device should be reviewed manually. Such kind of errors are potential candidate for hard reset at all.

```
2023-12-02T12:07:55.442Z INF/device:resources:minicap 35 [2..9] Installing "/opt/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch/minicap.apk" as "/data/local/tmp/minicap.apk"
2023-12-02T12:07:55.731Z INF/device:resources:service 35 [2..9] Checking whether we need to install STFService
2023-12-02T12:07:55.855Z INF/device:resources:service 35 [2..9] Installing STFService
2023-12-02T12:07:57.154Z FTL/device 35 [2..9] Setup had an error Error: /data/local/tmp/STFService.apk could not be installed [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package jp.co.cyberagent.stf could not be assigned a valid UID]
    at /opt/node_modules/@devicefarmer/adbkit/lib/adb/command/host-transport/install.js:28:23
    at processImmediate (node:internal/timers:466:21)
2023-12-02T12:07:57.155Z FTL/util:lifecycle 35 [2..9] Shutting down due to fatal error with optional error :  undefined
2023-12-02T12:07:57.173Z INF/provider 9 [*] Cleaning up device worker "2..9"
2023-12-02T12:07:57.174Z ERR/provider 9 [*] Device worker "2..9" died with code 1
2023-12-02T12:07:57.174Z INF/provider 9 [*] Restarting device worker "2..9"
```

no space left on device:
```
panther:/sdcard $ df -H /
Filesystem       Size Used Avail Use% Mounted on
/dev/block/dm-12 864M 862M     0 100% /
```

**Comment by vdelendik** [comment]
`2.6.2-beta`, communicate with me in advance to check that image is built correctly

**Comment by ignacionar** [comment]
**PR:** https://github.com/zebrunner/stf/pull/858

Steps to test: 

1. Clear cookies or test in new incognito window
2. Fill device memory, uninstall STFService 
3. Try to install it again when plugged as new

**Comment by dhreben** [comment]
Tested on stf:2.6.2-beta5 and mcloud-device:2.6.2-beta5

1. Disconnect device from linux
2. Uninstall the STFservice app on device
3. Full of all the memory on the device
4. Connect device to linux

**Actual result:** Device status has disconnected status on STF
**Expected result:** Device status has unhealthy status on STF

**Comment by dhreben** [comment]
**Tested on stf:2.6.2-beta9 and mcloud-device:2.6.2-beta9**



Still repro with STF UI status
Android device has disconnected status

<img width="1038" alt="Screenshot 2023-12-27 at 22 50 14" src="https://github.com/zebrunner/stf/assets/50950954/91d480d0-06c1-4b77-9040-08b80e5faf4b">



`logs from container`
```
2023-12-27T19:34:26.921Z INF/device:plugins:screen:stream 21 [LGH870S10681fc7] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:276) Publishing virtual display"
2023-12-27T19:34:26.926Z INF/device:plugins:screen:stream 21 [LGH870S10681fc7] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 12443652 bytes for JPG encoder"
2023-12-27T19:34:27.029Z INF/device:plugins:screen:stream 21 [LGH870S10681fc7] Reading minicap banner
2023-12-27T19:34:27.040Z INF/device:plugins:screen:stream 21 [LGH870S10681fc7] minicap says: "INFO: (jni/minicap/minicap.cpp:464) New client connection"
2023-12-27T19:39:45.402Z IMP/device:plugins:service 21 [LGH870S10681fc7] Service connection ended, attempting to relaunch
2023-12-27T19:39:45.402Z INF/device:plugins:service 21 [LGH870S10681fc7] Launching service
2023-12-27T19:39:45.402Z INF/device:plugins:service 21 [LGH870S10681fc7] using 'start-foreground-service' command for API 26
2023-12-27T19:39:46.157Z FTL/device:plugins:service 21 [LGH870S10681fc7] Service connection could not be relaunched Error: Service had an error: "Error: Not found; no service started."
    at /opt/lib/units/device/plugins/service.js:104:23
From previous event:
    at /opt/lib/units/device/plugins/service.js:79:14
    at processImmediate (node:internal/timers:466:21)
2023-12-27T19:39:46.157Z FTL/util:lifecycle 21 [LGH870S10681fc7] Shutting down due to fatal error with optional error :  undefined
2023-12-27T19:39:46.178Z INF/provider 8 [*] Cleaning up device worker "LGH870S10681fc7"
2023-12-27T19:39:46.179Z ERR/provider 8 [*] Device worker "LGH870S10681fc7" died with code 1
2023-12-27T19:39:46.180Z INF/util:lifecycle 8 [*] Winding down for graceful exit, with optional error :  ExitError: Exit code "1"
    at ChildProcess.exitListener (/opt/lib/units/provider/index.js:204:29)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 1
}
Warning: .then() only accepts functions but was passed: [object Object]
    at /opt/lib/units/provider/index.js:301:42
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Timeout.work [as _onTimeout] (/opt/lib/units/provider/index.js:285:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Unhandled rejection ExitError: Exit code "1"
    at ChildProcess.exitListener (/opt/lib/units/provider/index.js:204:29)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
2023-12-27T19:39:46.186Z WRN/db 8 [*] Connection closed
Exit status: 0

```

**Comment by dhreben** [comment]
Retested with **clear cache and cookies**

<img width="832" alt="Screenshot 2023-12-28 at 00 06 41" src="https://github.com/zebrunner/stf/assets/50950954/2065e17a-b80d-420f-a242-f16e96277c57">

**Comment by dhreben** [comment]
Verified
