### ISSUE TITLE
No control over device via farm UI in 2.6.2 release

### ISSUE THREAD

**Issue by azarouski** [zebrunner/stf#877]
When running `mcloud-device:2.6.2` ( `stf:2.6.2` ), i have no control over device screen with swipes and touches, but emulation of physical buttons works good.

<details>
  <summary>UI example</summary>
  <img width="200" alt="image" src="https://github.com/zebrunner/stf/assets/99244081/32f0d60b-cde2-4037-8d45-5569cce7d377">
</details>

<details>
  <summary>MCloud-device container logs</summary>
  
```js
2024-01-24T17:07:44.358057003Z 2024-01-24T17:07:44.349Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] stopping wda session:  3E6B932D-5E01-49A3-BBF8-F6BF91F036AE
2024-01-24T17:07:44.379729420Z 2024-01-24T17:07:44.375Z IMP/device:plugins:screen:stream 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] ws on close event
2024-01-24T17:07:44.407709545Z 2024-01-24T17:07:44.407Z IMP/device:plugins:group 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Now owned by "azarouski@solvd.com"
2024-01-24T17:07:44.408078670Z 2024-01-24T17:07:44.408Z INF/device:plugins:group 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Subscribing to group channel "YPrFQ/2qQvGLOoSdH75A/A=="
2024-01-24T17:07:44.420198337Z 2024-01-24T17:07:44.419Z VRB/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Request has been sent to WDA with data:  {"method":"DELETE","uri":"http://appium:8100/session/3E6B932D-5E01-49A3-BBF8-F6BF91F036AE"}
2024-01-24T17:07:45.545772837Z 2024-01-24T17:07:45.545Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] verifying wda session status...
2024-01-24T17:07:45.562655420Z 2024-01-24T17:07:45.562Z VRB/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Request has been sent to WDA with data:  {"method":"POST","uri":"http://appium:8100/session","body":{"capabilities":{}},"json":true}
2024-01-24T17:07:45.583103712Z 2024-01-24T17:07:45.582Z VRB/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/status","json":true}
2024-01-24T17:07:45.589234296Z 2024-01-24T17:07:45.589Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] status response: {"value":{"build":{"time":"Jan 23 2024 15:31:25","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.0","version":"17.0.2"},"device":"iphone","ios":{"ip":"192.168.3.131"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"B414E0F4-202C-4FA0-8918-D464180F999B"}
2024-01-24T17:07:45.589859337Z 2024-01-24T17:07:45.589Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] reusing existing wda session: B414E0F4-202C-4FA0-8918-D464180F999B
2024-01-24T17:07:45.591146004Z 2024-01-24T17:07:45.590Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Setting device version: 17.0.2
2024-01-24T17:07:45.592417337Z 2024-01-24T17:07:45.592Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] getting device window size...
2024-01-24T17:07:45.667508837Z 2024-01-24T17:07:45.667Z VRB/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/B414E0F4-202C-4FA0-8918-D464180F999B/orientation","json":true}
2024-01-24T17:07:45.671145379Z 2024-01-24T17:07:45.670Z INF/wdaClient 91 [XXXXXXXX-XXXXXXXXXXXXXXXX] Current device orientation: PORTRAIT
2024-01-24T17:07:45.714518796Z Unhandled rejection TypeError: Cannot read properties of undefined (reading 'message')
2024-01-24T17:07:45.714541462Z     at /opt/lib/units/ios-device/plugins/wda/WdaClient.js:690:44
2024-01-24T17:07:45.714543587Z     at tryCatcher (/opt/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
2024-01-24T17:07:45.714545421Z     at Promise._settlePromiseFromHandler (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:547:31)
2024-01-24T17:07:45.714547171Z     at Promise._settlePromise (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:18)
2024-01-24T17:07:45.714563754Z     at Promise._settlePromise0 (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:649:10)
2024-01-24T17:07:45.714566171Z     at Promise._settlePromises (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:725:18)
2024-01-24T17:07:45.714567796Z     at _drainQueueStep (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:93:12)
2024-01-24T17:07:45.714569754Z     at _drainQueue (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:86:9)
2024-01-24T17:07:45.714571462Z     at Async._drainQueues (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:102:5)
2024-01-24T17:07:45.714573129Z     at Immediate.Async.drainQueues [as _onImmediate] (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:15:14)
2024-01-24T17:07:45.714574837Z     at processImmediate (node:internal/timers:466:21)
2024-01-24T17:08:20.548062840Z node:events:505
2024-01-24T17:08:20.548099965Z       throw er; // Unhandled 'error' event
2024-01-24T17:08:20.548104715Z       ^
2024-01-24T17:08:20.548106465Z 
2024-01-24T17:08:20.548108048Z TypeError: Cannot read properties of null (reading 'width')
2024-01-24T17:08:20.548109673Z     at Object.swipe (/opt/lib/units/ios-device/plugins/util/iosutil.js:103:44)
2024-01-24T17:08:20.548111256Z     at Object.swipe (/opt/lib/units/ios-device/plugins/wda/WdaClient.js:275:31)
2024-01-24T17:08:20.548112840Z     at Router.<anonymous> (/opt/lib/units/ios-device/plugins/wda.js:48:19)
2024-01-24T17:08:20.548114840Z     at Router.emit (/opt/node_modules/eventemitter3/index.js:118:35)
2024-01-24T17:08:20.548116381Z     at Router.<anonymous> (/opt/lib/wire/router.js:35:12)
2024-01-24T17:08:20.548117965Z     at exports.Socket.emit (node:events:539:35)
2024-01-24T17:08:20.548119548Z     at exports.Socket.Socket._emitMessage (/opt/node_modules/zeromq/lib/index.js:649:15)
2024-01-24T17:08:20.548121173Z     at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:660:10)
2024-01-24T17:08:20.548122840Z     at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
2024-01-24T17:08:20.548124465Z     at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
2024-01-24T17:08:20.548126090Z     at processImmediate (node:internal/timers:466:21)
2024-01-24T17:08:20.548127631Z Emitted 'error' event on  instance at:
2024-01-24T17:08:20.548129173Z     at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:662:10)
2024-01-24T17:08:20.548130756Z     at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
2024-01-24T17:08:20.548132340Z     at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
2024-01-24T17:08:20.548133923Z     at processImmediate (node:internal/timers:466:21)
2024-01-24T17:08:20.548291090Z 
2024-01-24T17:08:20.548308673Z Node.js v17.9.0
2024-01-24T17:08:20.599099173Z Exit status: 1
```

</details>

Perhaps the problem is hidden here -> https://github.com/zebrunner/stf/commit/8c0f75a60e87b6165daf223ad79ce33b6186418b#diff-c0e662c394d4f7f25b37555bc7982efa0f05f9595025a9cb82e9c4fec91884c4L458-R459

**Comment by dhreben** [comment]
Issue was repro with install from **mcloud-ios** and **mcloud- android** from scratch

**Comment by dhreben** [comment]
Tested and fixed
**public.ecr.aws/zebrunner/stf:2.6.3-beta1**
**public.ecr.aws/zebrunner/mcloud-device:2.6.1-beta1**
