### ISSUE TITLE
Impossible to do swipe actions on iOS devices after setup from scratch on master branch

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#883]
```

2024-02-07T09:30:21.534Z INF/wdaClient 65 [6d1e6edcda98119a61f67b69424ba20454603216] Current device orientation: PORTRAIT
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'message')
    at /opt/lib/units/ios-device/plugins/wda/WdaClient.js:695:44
    at tryCatcher (/opt/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/node_modules/request-promise/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
2024-02-07T09:31:38.103Z VRB/wda:client 65 [6d1e6edcda98119a61f67b69424ba20454603216] wire.TypeMessage:  { key: 'home' }
2024-02-07T09:31:38.715Z VRB/wdaClient 65 [6d1e6edcda98119a61f67b69424ba20454603216] Request has been sent to WDA with data:  {"method":"POST","uri":"http://appium:8100/session/0968833A-5027-4312-96A0-3B5F99152249/wda/pressButton","body":{"name":"home"},"json":true}
2024-02-07T09:31:38.740Z VRB/wdaClient 65 [6d1e6edcda98119a61f67b69424ba20454603216] Request has been sent to WDA with data:  {"method":"POST","uri":"http://appium:8100/session/0968833A-5027-4312-96A0-3B5F99152249/orientation","body":{"orientation":"PORTRAIT"},"json":true}
2024-02-07T09:31:38.741Z INF/wdaClient 65 [6d1e6edcda98119a61f67b69424ba20454603216] getting device window size...
2024-02-07T09:31:38.756Z VRB/wdaClient 65 [6d1e6edcda98119a61f67b69424ba20454603216] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/0968833A-5027-4312-96A0-3B5F99152249/orientation","json":true}

```

**Comment by dhreben** [comment]
Merged to develop

**Comment by dhreben** [comment]
Fixed
Tested on versions: 
DEVICE_VERSION: 2.6.4-beta1
STF :  2.6.4-beta1
