### ISSUE TITLE
stf-processor server is broken by saveDeviceInitialState method

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#915]
```
2024-03-07T16:47:53.318Z INF/db 1 [*] Connecting to rethinkdb:28015
2024-03-07T16:47:53.343Z INF/processor 1 [proc001] Device dealer connected to "tcp://stf-triproxy-dev:7260"
node:events:505
      throw er; // Unhandled 'error' event
      ^

ReferenceError: message is not defined
    at Object.dbapi.saveDeviceInitialState (/opt/lib/db/api.js:1132:48)
    at Router.<anonymous> (/opt/lib/units/processor/index.js:60:13)
    at Router.emit (/opt/node_modules/eventemitter3/index.js:144:27)
    at Router.<anonymous> (/opt/lib/wire/router.js:35:12)
    at exports.Socket.emit (node:events:527:28)
    at exports.Socket.Socket._emitMessage (/opt/node_modules/zeromq/lib/index.js:649:15)
    at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:660:10)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
    at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
    at processImmediate (node:internal/timers:466:21)
Emitted 'error' event on  instance at:
    at exports.Socket.Socket._flushRead (/opt/node_modules/zeromq/lib/index.js:662:10)
    at exports.Socket.Socket._flushReads (/opt/node_modules/zeromq/lib/index.js:696:15)
    at Immediate.<anonymous> (/opt/node_modules/zeromq/lib/index.js:307:12)
    at processImmediate (node:internal/timers:466:21)

Node.js v17.9.0

```

**Comment by vdelendik** [comment]
fixed and verified successfully
