### ISSUE TITLE
bump up  Pixel 7 on Andoroid 14

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#951]
- Pixel 7 Android
- Appium 2.0

**Actual result:** Device has preparing status on STF

**Container log:** 

```
2023-08-09T08:54:27.903Z FTL/util:lifecycle 113 [2A09.......0DR0] Shutting down due to fatal error with optional error :  undefined
2023-08-09T08:54:27.918Z INF/provider 8 [*] Cleaning up device worker "2A.......DR0"
2023-08-09T08:54:27.918Z ERR/provider 8 [*] Device worker "2A0.......0DR0" died with code 1
2023-08-09T08:54:27.918Z INF/provider 8 [*] Restarting device worker "2A09.......DR0"
2023-08-09T08:54:28.989Z INF/db 134 [2A09........0DR0] Connecting to rethinkdb:28015
2023-08-09T08:54:29.006Z INF/device:support:push 134 [2A09.......DR0] Sending output to "tcp://stf-triproxy-dev:7270"
2023-08-09T08:54:29.014Z INF/device 134 [2A0.......0DR0] Preparing device
2023-08-09T08:54:29.953Z INF/device:support:sub 134 [2A0........0DR0] Receiving input from "tcp://stf-triproxy-dev:7250"
2023-08-09T08:54:29.956Z INF/device:support:sub 134 [2A0...........0DR0] Subscribing to permanent channel "*ALL"
2023-08-09T08:54:30.106Z INF/device:support:properties 134 [2A............0DR0] Loading properties
2023-08-09T08:54:30.147Z INF/device:support:sdk 134 [2A..............R0] Supports SDK 34
2023-08-09T08:54:30.149Z INF/device:support:abi 134 [2A09............DR0] Supports ABIs arm64-v8a
2023-08-09T08:54:30.467Z INF/device:resources:minicap 134 [2A...........DR0] Installing "/opt/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch/minicap.apk" as "/data/local/tmp/minicap.apk"
2023-08-09T08:54:30.738Z INF/device:resources:service 134 [2A..............DR0] Checking whether we need to install STFService
2023-08-09T08:54:30.851Z INF/device:resources:service 134 [2A..............0DR0] Running version check
2023-08-09T08:54:31.934Z INF/device:resources:service 134 [2A..............DR0] STFService up to date
2023-08-09T08:54:31.935Z INF/device:plugins:service 134 [2A0...........DR0] Launching agent
2023-08-09T08:54:32.497Z INF/device:plugins:service 134 [2A.............0DR0] Agent says: "Starting minitouch agent"
2023-08-09T08:54:32.509Z INF/device:plugins:service 134 [2A0.............0DR0] Agent says: "java.lang.NoSuchMethodException: android.view.IWindowManager$Stub$Proxy.injectKeyEvent [class android.view.KeyEvent, boolean]"
2023-08-09T08:54:32.510Z INF/device:plugins:service 134 [2A0..........0DR0] Agent says: "at java.lang.Class.getMethod(Class.java:2937)"
2023-08-09T08:54:32.511Z INF/device:plugins:service 134 [2A0.........0DR0] Agent says: "at java.lang.Class.getMethod(Class.java:2449)"
2023-08-09T08:54:32.512Z INF/device:plugins:service 134 [2A09..............0DR0] Agent says: "at jp.co.cyberagent.stf.compat.InputManagerWrapper$WindowManagerEventInjector.<init>(InputManagerWrapper.java:93)"
2023-08-09T08:54:32.513Z INF/device:plugins:service 134 [2..............0DR0] Agent says: "at jp.co.cyberagent.stf.compat.InputManagerWrapper.<init>(InputManagerWrapper.java:19)"
2023-08-09T08:54:32.515Z INF/device:plugins:service 134 [2A09.................0DR0] Agent says: "at jp.co.cyberagent.stf.MinitouchAgent.<init>(MinitouchAgent.java:288)"
2023-08-09T08:54:32.516Z INF/device:plugins:service 134 [2A0............0DR0] Agent says: "at jp.co.cyberagent.stf.Agent.main(Agent.java:65)"
2023-08-09T08:54:32.521Z INF/device:plugins:service 134 [2A09..........DR0] Agent says: "at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)"
2023-08-09T08:54:32.522Z INF/device:plugins:service 134 [2A0.........0DR0] Agent says: "at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)"
2023-08-09T08:54:36.753Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "2A09............DR0"
2023-08-09T08:54:42.297Z FTL/device 134 [2A.........00DR0] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

**Mobile-Android-Demo-Test Log:**

```
11:53:39  2023-08-09 08:53:39 Messager [TestNG-test=Mobile test-1-30] [ERROR] TEST [Mobile test - testUIElements] FAILED at [08:53:39 2023-08-09] - Could not start a new session. Response code 500. Message: Error forwarding the new session cannot find : Capabilities {appium:app: https://qaprosoft.s3-us-wes/..., appium:automationName: UIAutomator2, appium:deviceName: Pixel_7, appium:enableLog: true, appium:enableVideo: true, appium:language: en, appium:locale: US, appium:provider: mcloud, appium:remoteAppsCacheLimit: 0, platformName: android} 
11:53:39  Host info: host: '171a1b139384', ip: '172.18.0.3'
11:53:39  Build info: version: '4.7.0', revision: '0a5b49d16f'
11:53:39  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-142-generic', java.version: '17.0.7'
11:53:39  Driver info: io.appium.java_client.android.AndroidDriver
11:53:39  Command: [null, newSession {capabilities=[{appium:enableLog=true, appium:provider=mcloud, appium:enableVideo=true, appium:locale=US, appium:language=en, appium:remoteAppsCacheLimit=0, appium:deviceName=Pixel_7, platformName=ANDROID, appium:automationName=UIAutomator2, appium:app=[https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk}](https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk%7D)], desiredCapabilities=Capabilities {appium:app: https://qaprosoft.s3-us-wes/..., appium:automationName: UIAutomator2, appium:deviceName: Pixel_7, appium:enableLog: true, appium:enableVideo: true, appium:language: en, appium:locale: US, appium:provider: mcloud, appium:remoteAppsCacheLimit: 0, platformName: ANDROID}}]
11:53:39  Capabilities {}
11:53:39  
11:53:39  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:53:39  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:53:39  java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:53:39  io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
11:53:39  io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
11:53:39  io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:194)
11:53:39  io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
11:53:39  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
11:53:39  io.appium.java_client.AppiumDriver.startSession$original$M7jckjeS(AppiumDriver.java:229)
11:53:39  io.appium.java_client.AppiumDriver.startSession$original$M7jckjeS$accessor$M64xGaNd(AppiumDriver.java)
11:53:39  io.appium.java_client.AppiumDriver$auxiliary$Xmft43MA.run(Unknown Source)
11:53:39  com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:42)
11:53:39  io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java)
11:53:39  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
11:53:39  io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
11:53:39  io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
11:53:39  io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:231)
11:53:39  com.zebrunner.carina.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:106)
11:53:39  com.zebrunner.carina.webdriver.core.factory.DriverFactory.create(DriverFactory.java:86)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.createDriver(IDriverPool.java:364)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:117)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:80)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:68)
11:53:39  com.zebrunner.carina.demo.MobileSampleTest.testUIElements(MobileSampleTest.java:81)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:53:39  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:53:39  java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:53:39  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
11:53:39  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
11:53:39  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
11:53:39  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
11:53:39  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
11:53:39  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
11:53:39  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
11:53:39  java.base/java.lang.Thread.run(Thread.java:833)
11:53:39  2023-08-09 08:53:39 Messager [TestNG-test=Mobile test-1-30] [INFO] TEST [Mobile test - testWebView] STARTED at [08:53:39 2023-08-09]
11:53:39  2023-08-09 08:53:39 DriverFactory [TestNG-test=Mobile test-1-30] [INFO] Starting driver session...
11:53:39  2023-08-09 08:53:39 Messager [TestNG-test=Mobile test-1-30] [ERROR] TEST [Mobile test - testWebView] FAILED at [08:53:39 2023-08-09] - Could not start a new session. Response code 500. Message: Error forwarding the new session cannot find : Capabilities {appium:app: https://qaprosoft.s3-us-wes/..., appium:automationName: UIAutomator2, appium:deviceName: Pixel_7, appium:enableLog: true, appium:enableVideo: true, appium:language: en, appium:locale: US, appium:provider: mcloud, appium:remoteAppsCacheLimit: 0, platformName: android} 
11:53:39  Host info: host: '171a1b139384', ip: '172.18.0.3'
11:53:39  Build info: version: '4.7.0', revision: '0a5b49d16f'
11:53:39  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-142-generic', java.version: '17.0.7'
11:53:39  Driver info: io.appium.java_client.android.AndroidDriver
11:53:39  Command: [null, newSession {capabilities=[{appium:enableLog=true, appium:provider=mcloud, appium:enableVideo=true, appium:locale=US, appium:language=en, appium:remoteAppsCacheLimit=0, appium:deviceName=Pixel_7, platformName=ANDROID, appium:automationName=UIAutomator2, appium:app=[https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk}](https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk%7D)], desiredCapabilities=Capabilities {appium:app: https://qaprosoft.s3-us-wes/..., appium:automationName: UIAutomator2, appium:deviceName: Pixel_7, appium:enableLog: true, appium:enableVideo: true, appium:language: en, appium:locale: US, appium:provider: mcloud, appium:remoteAppsCacheLimit: 0, platformName: ANDROID}}]
11:53:39  Capabilities {}
11:53:39  
11:53:39  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:53:39  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:53:39  java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:53:39  io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
11:53:39  io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
11:53:39  io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:194)
11:53:39  io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
11:53:39  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
11:53:39  io.appium.java_client.AppiumDriver.startSession$original$M7jckjeS(AppiumDriver.java:229)
11:53:39  io.appium.java_client.AppiumDriver.startSession$original$M7jckjeS$accessor$M64xGaNd(AppiumDriver.java)
11:53:39  io.appium.java_client.AppiumDriver$auxiliary$Xmft43MA.run(Unknown Source)
11:53:39  com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:42)
11:53:39  io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java)
11:53:39  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
11:53:39  io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
11:53:39  io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
11:53:39  io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:231)
11:53:39  com.zebrunner.carina.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:106)
11:53:39  com.zebrunner.carina.webdriver.core.factory.DriverFactory.create(DriverFactory.java:86)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.createDriver(IDriverPool.java:364)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:117)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:80)
11:53:39  com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:68)
11:53:39  com.zebrunner.carina.demo.MobileSampleTest.testWebView(MobileSampleTest.java:59)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:53:39  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:53:39  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:53:39  java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:53:39  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
11:53:39  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
11:53:39  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
11:53:39  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
11:53:39  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
11:53:39  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
11:53:39  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
11:53:39  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
11:53:39  java.base/java.lang.Thread.run(Thread.java:833)
11:53:40  2023-08-09 08:53:39 Messager [main-1] [INFO] INFO: '**************** Test execution summary ****************'.
11:53:40  2023-08-09 08:53:39 Messager [main-1] [INFO] RESULT zebrunner/appium#1: TEST [Mobile test - testLoginUser] FAIL [log=[https://demo.zebrunner.farm:443/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/b5d7ce1f-a564-4c30-8c17-f0002c49c3cd/test.log](https://demo.zebrunner.farm/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/b5d7ce1f-a564-4c30-8c17-f0002c49c3cd/test.log)]
11:53:40  2023-08-09 08:53:39 Messager [main-1] [INFO] RESULT zebrunner/appium#2: TEST [Mobile test - testUIElements] FAIL [log=[https://demo.zebrunner.farm:443/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/0d16f163-2fb5-4f70-b589-80eaf75b26ca/test.log](https://demo.zebrunner.farm/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/0d16f163-2fb5-4f70-b589-80eaf75b26ca/test.log)]
11:53:40  2023-08-09 08:53:39 Messager [main-1] [INFO] RESULT zebrunner/appium#3: TEST [Mobile test - testWebView] FAIL [log=[https://demo.zebrunner.farm:443/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/13d29846-4e33-4897-bf29-1f8cc8440836/test.log](https://demo.zebrunner.farm/jenkins/job/qps/job/carina-demo/job/Mobile-Android-Demo-Test/7/ZebrunnerReport/1691571190233/13d29846-4e33-4897-bf29-1f8cc8440836/test.log)]
11:53:40  [ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 34.414 s <<< FAILURE! - in TestSuite
11:53:40  [ERROR] com.zebrunner.carina.demo.MobileSampleTest.testLoginUser  Time elapsed: 9.496 s  <<< FAILURE!
11:53:40  org.openqa.selenium.SessionNotCreatedException:
```

**Comment by vdelendik** [comment]
same ticket in original stf: https://github.com/DeviceFarmer/stf/issues/692
it refers to the https://github.com/DeviceFarmer/STFService.apk/issues/130 which seems should be fixed in latest STFService.apk

@dhreben, could you please install manually https://github.com/DeviceFarmer/STFService.apk/releases/tag/v2.5.2 and test again vs problematic device.

**Comment by dhreben** [comment]
Successfully tested after added to device container  STFService v2.5.2 https://github.com/DeviceFarmer/STFService.apk/releases/tag/v2.5.2

`docker cp STFService.apk ab61f7d0882a:opt/vendor/STFService/STFService.apk`

**Comment by dhreben** [comment]
STFService v2.5.2 will be added to new Appium 2.1.0

**Comment by vdelendik** [comment]
@dhreben - deployed on stage.
STFService.apk is inside `public.ecr.aws/zebrunner/stf:2.7.0-beta3` and `public.ecr.aws/zebrunner/mcloud-device:2.7.0-beta5`

**Comment by dhreben** [comment]
Fixed.
